# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
---
name: Feature Request
description: Suggest a new feature or improvement.
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you would like to see.
      placeholder: Please describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would this feature help you? What problem does it solve?
      placeholder: Describe your use case.
    validations:
      required: false
